services:
  # 1. DATABASE
  mysql:
    image: mysql:8.0
    container_name: scriptify-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: scriptify
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - scriptify-network
    # Thêm healthcheck để Backend biết khi nào DB thực sự sẵn sàng
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. BACKEND
  backend:
    build: ./backend
    container_name: scriptify-be
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy # Chỉ chạy khi DB đã khoẻ mạnh
    environment:
      # LƯU Ý: Trong Docker network, bồ thay 'localhost' bằng 'mysql'
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

    networks:
      - scriptify-network

  # 3. FRONTEND
  frontend:
    build: 
      context: ./frontend
      args:
        # Truyền URL R2 và Backend vào lúc build Vite
        - VITE_R2_PUBLIC_URL=${VITE_R2_PUBLIC_URL}
    container_name: scriptify-fe
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - scriptify-network

networks:
  scriptify-network:
    driver: bridge

volumes:
  mysql-data: