spring.application.name=scriptify

server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/

# JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]

# Upload directories
app.upload.music-dir=uploads/music
app.upload.image-dir=uploads/images

# Multipart limits (adjust as needed)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.orm.results=TRACE
logging.level.org.hibernate.resource.jdbc.type.descriptor.sql.BasicBinder=TRACE