spring.application.name=scriptify

server.port=${PORT:8443}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/

# JWT secret key
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000

# Cấu hình SMTP của Resend
spring.mail.host=smtp.resend.com
spring.mail.port=587
spring.mail.username=resend
spring.mail.password=${RESEND_API_KEY}

# Cấu hình giao thức bảo mật
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Định nghĩa thêm một biến custom cho Email gửi đi (Bắt buộc phải là tên miền đã verify trên Resend)
app.mail.from=Scriptify <no-reply@xcode.id.vn>

# R2 Cloudflare
r2.endpoint: https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com
r2.access-key: ${R2_ACCESS_KEY_ID}
r2.secret-key: ${R2_SECRET_ACCESS_KEY}
r2.bucket-name: ${R2_BUCKET_NAME}
r2.public-url: ${R2_PUBLIC_URL}

spring.config.import=optional:file:.env[.properties]

# Multipart limits (adjust as needed)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

logging.level.org.hibernate.orm.results=TRACE
logging.level.org.hibernate.resource.jdbc.type.descriptor.sql.BasicBinder=TRACE

# Swagger UI
springdoc.override-with-generic-response=false
